{"name": "Тест авторизации с неверным логином и паролем", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@pytest.fixture\n    def user_data_and_token():\n        payload = helpers.payload\n        response = requests.post(UrlsConstants.CREATE_USER, data=payload)\n>       token = response.json()['accessToken']\nE       KeyError: 'accessToken'\n\ntests\\conftest.py:11: KeyError"}, "description": "Получение ошибки. Авторизация не выполнена", "start": 1727882466559, "stop": 1727882466559, "uuid": "68ab52d3-0a90-4fb1-b318-2f22359c5973", "historyId": "7d8ee533535a2ed61f3922b2354a854f", "testCaseId": "7d8ee533535a2ed61f3922b2354a854f", "fullName": "tests.test_api_login_user.TestLoginUser#test_login_user_incorrect_email_and_password_error", "labels": [{"name": "feature", "value": "Проверка авторизации пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-E2MLG10"}, {"name": "thread", "value": "14732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_login_user"}]}